doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: '%env(POSTGRES_DB)%'
                host: '%env(POSTGRES_HOST)%'
                port: '%env(POSTGRES_PORT)%'
                user: '%env(POSTGRES_USER)%'
                password: '%env(POSTGRES_PASSWORD)%'
                driver: pdo_pgsql
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
